name: asdasd
favicon: null
layout_spectrum: 0.17072055162861943
typography_spectrum: 0.7126784394495189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7944634975865483
  lightness: 0.1625836151652038
  saturation: 0.08967278711497784
  rhythmicContrast: 0.4142929310910404
purpose: []
